### ISSUE TITLE
Authenticate programmatically failing in test-suite but working when launching tests independently 

### ISSUE THREAD

**Issue by dupuchba** [Behat/Symfony2Extension#109]
I am working an application that id doing an authentication on a 3rd provider with a `PreAuthenticatedToken`.

To fake the authentication without doing the request to the 3rd provider, I create a new step definition which is setting the token in the tokenStorage like this (without using sessions):

```
public function iAuthenticateMysel()
    {
        $user = new User(
            '1',
            null,
            ['ROLE_USER']
        );

        $token = new PreAuthenticatedToken(
            $user,
            '62fb6xyy3wws80o0gs4wk08kg0wkss08c0cok8cckgcc4gs0gk',
            'secured_area',
            $user->getRoles()
        );

        $this->getContainer()->get('security.token_storage')->setToken($token);
    }
```

This is working when I launch scenario 1by1 but failing with the tessuite. 
Here are my question : 
- Do I authenticate users well ?
- What am I missing

Thanks for your help,

Baptiste

**Comment by sroze** [comment]
Hey @dupuchba. My recommendation for such cases is to override the implementation of your "authenticator" (the service that talk with your 3rd party) in the `test` environment (or the Symfony environment you're using).

You can simply uses the `services` definitely in your `config_test.yml` file. I'm not fond of self-promotion but as I can see you're French, here's [a short presentation I gave at the Forum PHP last year](https://www.youtube.com/watch?v=OioLX7HLt5s) about that topic, so if it's unclear, that will probably help you.

**Comment by dupuchba** [comment]
ok, I'll look ! by the way, how bad is my english to make you guess that I am french ^^ ?

**Comment by sroze** [comment]
Haha, no worries, your name and Google told me that.

**Comment by dupuchba** [comment]
@sroze , I just watched tour talk and I have to say that your describe the ideal behavior. I won't use it in this project , at least not right away as I found a solution that looks just find for my need (mock the the container and service). Thx for your help
