### ISSUE TITLE
New tagged version?

### ISSUE THREAD

**Issue by DonCallisto** [Behat/Symfony2Extension#129]
Hello.

It's been a long time since last tagged version and a there are a lot of commits only on `master` branch.

I suppose that a new tagged version could be released including all or a subset of this commits.

WDYT?

**Comment by sroze** [comment]
That's a good idea. Is `master` working 👌 for you?

**Comment by DonCallisto** [comment]
For a big app we develop, this bundle is included with `dev-master` since months. 
We update packages weekly; no particular issues raised.

Don't know if our "case study" is a good proof but we use a lot behat and this extension if this can give you some hints.

**Comment by DonCallisto** [comment]
@sroze I've also made this 130 to fix travis builds

**Comment by sroze** [comment]
We have tags :-)

**Comment by DonCallisto** [comment]
Thank you!
