### ISSUE TITLE
BC Break introduced in 2.1.2

### ISSUE THREAD

**Issue by jonag** [Behat/Symfony2Extension#132]
I think that [this PR](https://github.com/Behat/Symfony2Extension/pull/111) introduced a BC Break in the version 2.1.2.

I don't provide any value for the parameter `symfony2_extension.kernel.bootstrap` so [the extension uses the default value `'app/autoload.php'`](https://github.com/Behat/Symfony2Extension/blob/4eec9ec8dec86c24d82d50b072e693ff2e98ecca/src/Behat/Symfony2Extension/ServiceContainer/Symfony2Extension.php#L73).

Since the file `app/autoload.php` doesn't exist on my project, behat is now throwing an exception when I try to execute my tests.

I have fixed the issue by setting manually the value to `~` for the parameter (don't know if it's what I'm supposed to do, but since the file never existed and the tests are working...).

I can try to prepare a PR to fix or document this case, depending of what you want to do.

**Comment by sroze** [comment]
Yes, you are correct. #135 is meant to fix that.

**Comment by sroze** [comment]
Actually fixed in Behat 3.4.3

**Comment by sroze** [comment]
Fix is merged 👍
