### ISSUE TITLE
Symfony event listeners not supported ?

### ISSUE THREAD

**Issue by smtlab** [Behat/Symfony2Extension#138]
I recently found that Behat is not executing any of the event listeners defined in app bundle, tried some tests which involved Symfony event listeners. But seems like there's no support.

Need help!

**Comment by jon-acker** [comment]
With the Symfont2 extension, the Symfony app behaves exactly as it does normally - any tagged event listeners will be called. Are you sure the listeners are not called when you run the app from the  Behat?

**Comment by smtlab** [comment]
My bad I forgot to register a bundle in my app kernel.
You can close this issue. Sorry for the inconvenience :)
