### ISSUE TITLE
Container services are re-instantiated several times in a single scenario

### ISSUE THREAD

**Issue by tiraeth** [Behat/Symfony2Extension#25]
Hi,

I've ran into a huge problem this morning. I am using external API which provides limitations for it's usage. So I decided to create stubbed connection with response mechanism working as a stack of responses. Everything works in PHPUnit, but when I run behat tests and expect to be able to prepare response stack in **@BeforeScenario** event, it does not work at all. I was surpised to see that response stack is emptied before each step.

I added simple `echo` in service's constructor and found out that **the service's constructor is called multiple times** in a single scenario. That's interesting, because `setKernel` on the context is called only once.

Can anyone explain to me what's going on and how to prevent services from being re-instantiated between steps and why it is exactly three times for 2-step scenario?

**Comment by jon-acker** [comment]
@tiraeth on every separate request handled by Symfony, kernel is rebooted and the container will be rebuilt - if that is the cause of your problem, there is another work-around.

**Comment by ribb3r** [comment]
@jon-acker Could you please provide an example for the workaround? Thank you.
