### ISSUE TITLE
Set path parameters correctly when running bundle test suites

### ISSUE THREAD

**Issue by ged15** [Behat/Symfony2Extension#45]
Hello!

Currently, when running a test suite for a bundle, the path parameters (%behat.paths.features% and %behat.paths.bootstrap%) are set relative to the project root dir, not the bundle dir (i.e. /var/www/features instead of /var/www/src/Acme/DemoBundle/Features). IMO they should be set relative to the bundle dir. If anybody agrees I could look into it that's possible.

**Comment by sroze** [comment]
The current behaviour seams coherent to me. Are you still experiencing the problem @ged15 and believe we should change something?

**Comment by ged15** [comment]
Hey!
Sorry for the inactivity. I was using Behat 2.5 back then. Now I do not use per-bundle test suites, so don't know of the status anymore :)
Closing.
