### ISSUE TITLE
Too many connections - Doctrine connections are not closed

### ISSUE THREAD

**Issue by mathroc** [Behat/Symfony2Extension#52]
When running tests, it seems the extension "start" a new Symfony env for each feature (which is great), however the Doctrine connections of older env are not closed and it causes 'Too many connections' after a while

I had to add this to get past it:

```php
    /**
     * @AfterScenario
     */
    public function closeConnections($event)
    {
        $doctrine = $this->getDoctrine();
        foreach ($doctrine->getManagers() as $name => $entityManager) {
            $entityManager->close();
            $connection->close();
        }
    }
```

**Comment by stof** [comment]
I sent a PR on DoctrineBundle to fix this issue. Can you try my branch to see whether it works ?

**Comment by Renrhaf** [comment]
Hello @stof,

I use the method described here : symfony/symfony-docs#4049
To automatically rollback any changes in my tests.

But these modifications seems to break it since it closes the entity manager after every test.
Do you think of a workaround to still be able to use it ?

Regards,
Renrhaf

**Comment by dypa** [comment]
@stof i confirm that your patch works for me (after update to "doctrine/doctrine-bundle": "1.4.*"), thanks!
