### ISSUE TITLE
kernel booted twice

### ISSUE THREAD

**Issue by ftassi** [Behat/Symfony2Extension#55]
Hi,

I'm working with behat 2.5 and extension 1.x and I noticed that the kernel is booted twice, not sure if this is somehow needed or if is a issue.

At https://github.com/Behat/Symfony2Extension/blob/1.1.x/src/Behat/Symfony2Extension/Compiler/KernelInitializationPass.php#L58 the kernel is booted first time and then in https://github.com/Behat/Symfony2Extension/blob/1.1.x/src/Behat/Symfony2Extension/Context/Initializer/KernelAwareInitializer.php#L114 it is booted again.

KernelAwareInitializer is listening for beforeScenario. This is resulting in the kernel booting at behat startup and then before each scenario. 

In my case this is an issue because I'm trying to test a bundle and I need to manipulate my kernel (i have a fixtures app) before it's booted.

As far as I know this could be solved by behat 3.0 and the new version of the extension (not sure, didn't checked yet) but I'm not sure if I want to switch to 3.0 before it is stable though.

**Comment by sroze** [comment]
Closing because of #101, we drop support of Behat 2.

@ftassi you can also have a look to #88, this is a related issue.
