### ISSUE TITLE
Commands bin/behat --init and bin/behat --init "@CompanyDemoBundle" don't create the same folder structure

### ISSUE THREAD

**Issue by kenden** [Behat/Symfony2Extension#56]
When initializing behat, 
* the command
$ bin/behat --init
creates a directory 'features' in the current directory. 
Inside, there is the folder 'bootstrap', and inside bootstrap, 'FeatureContext.php'

* the command
$ bin/behat --init "@CompanyDemoBundle"
creates a directory 'Features' in src/Company/DemoBundle/
Inside, there is the folder 'Context', and inside bootstrap, 'FeatureContext.php'

The directory structure should be the same in both cases, but differs
...feature/bootstrap/FeatureContext.php
...Feature/Context/FeatureContext.php
(features has a capital letter. The directory bootstrap and Context have different names)

Steps to reproduce
-----------------------------
* Install behat via composer. Add the following in composer.json
"require-dev": {
        "behat/behat": "*@stable",
        "behat/symfony2-extension": "*@stable",
        "behat/mink": "*@stable",
        "behat/mink-extension": "*@stable",
        "behat/mink-browserkit-driver": "*@stable",
    }
* Type command
$ bin/behat --init
---> directory 'features' is created in the current directory. 
      Inside is the folder 'bootstrap', and inside, 'FeatureContext.php'

* Activate the Symfony2Extension extension in behat.yml:
    default:
        # ...
        extensions:
            Behat\Symfony2Extension\Extension: ~
* Type command
$ bin/behat --init "@CompanyDemoBundle"
---> directory 'Features' is created in src/Company/DemoBundle/
Inside, there is the folder 'Context', and inside bootstrap, 'FeatureContext.php'

**Comment by stof** [comment]
Closing because @andrewmatthews explained the reason of this behavior
