### ISSUE TITLE
Extension file or class could not be located

### ISSUE THREAD

**Issue by sprain** [Behat/Symfony2Extension#65]
I am using Behat 3 on dev-master and Symfony2Extension on dev-master. I keep getting this error: 

```
[Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]  
`Behat\Symfony2Extension\Extension` extension file or class could not be located. 
```

I see that `Behat\Symfony2Extension\Extension` doesn't exist anymore in this version. But what would be the correct extension location to look for?

**Comment by sampart** [comment]
Could you explain further where you found a solution please?

**Comment by everzet** [comment]
https://github.com/Behat/Symfony2Extension/blob/master/doc/index.rst

**Comment by sampart** [comment]
Thank you.  I see what's wrong now - I had to change `Behat\Symfony2Extension\Extension:` to `Behat\Symfony2Extension:` in my behat.yml.

**Comment by xtrasmal** [comment]
Setting up Behat always gives me headaches. I've done it a couple of times on Laravel, but now on Symfony2 it tells me that the Extension can't be found. 
What is the correct way?  

    Behat\Symfony2Extension\ServiceContainer: ~

or

    Behat\Symfony2Extension: ~
?

The last one gives me 

     [Behat\Testwork\ServiceContainer\Exception\ExtensionInitializationException]  
     `Behat\Symfony2Extension` extension file or class could not be located.

**Comment by sampart** [comment]
@xtrasmal If you're using Behat 2 (which it sounds like you are), it's:

    Behat\Symfony2Extension\Extension: ~

If you were using Behat 3, the second example you gave would be correct:

    Behat\Symfony2Extension: ~

**Comment by stof** [comment]
Given the exception message, it looks like Behat 3 is used (there is no Testwork in Behat 2).

Have you installed the Symfony2Extension ? To be able to register it, the class needs to be autoloadable. When using Composer, the autoloading should already be handled for you btw

**Comment by xtrasmal** [comment]
Hi guys. It's a Symfony2 project installed using composer. Running:

    "behat/behat": "~3.0",
    "behat/symfony2-extension": "~2.0"

And my behat.yml: 

    default:
          suites:
            default:
                    contexts:
            - FeatureContext:
                session:   '@session'
      extensions:
        Behat\Symfony2Extension: ~
