### ISSUE TITLE
Incompatibility with "var/" kernel root dir

### ISSUE THREAD

**Issue by gquemener** [Behat/Symfony2Extension#69]
Hello,

I've activated the new directory structure using var/ as root dir for the cache, logs, etc.
The Symfony2Extension keeps creating app/cache and app/logs directories.

I'm finding a solution to enhance the extension, but haven't found yet how Symfony2 manage to override the kernel root directory (I thought it would have been done in app/AppKernel.php)

**Comment by smatyas** [comment]
I've just run into this issue.
It seems that the SensioDistributionBundle generates the correct getters into the `bootstrap.php.cache` This file is loaded in the `app_dev.php`, therefore that is working.
So I think it's save to add these two methods to the `AppKernel`:
```php
    public function getCacheDir()
    {
        return $this->rootDir.'/../var/cache/'.$this->environment;
    }

    public function getLogDir()
    {
        return $this->rootDir.'/../var/logs';
    }
```
Maybe the SensioDistributionBundle should patch the AppKernel this way, but there is an ongoing development about this: https://github.com/sensiolabs/SensioDistributionBundle/issues/117

**Comment by stof** [comment]
Closing because this is a bug in SensioDistributionBundle when initializing the Symfony2 directory structure: https://github.com/sensiolabs/SensioDistributionBundle/issues/142#issuecomment-68713604. The fix is given in the comment of @smatyas just above.
