### ISSUE TITLE
Wrong feature path generation

### ISSUE THREAD

**Issue by arnaugm** [Behat/Symfony2Extension#75]
Apparently there is an error in the generation of the features path in src/Behat/Symfony2Extension/Console/Processor/LocatorProcessor.php:99 that prevents behat working properly in some cases, for example through PhpStorm.
Please have a look at this threat for more details
https://youtrack.jetbrains.com/issue/WI-24974

Used version: v1.1.2

**Comment by sroze** [comment]
Closing because of #101, we drop support of Behat 2.
