### ISSUE TITLE
Behat 3 complains if an array is passed as a parameter to a context when Symfony2Extension is enabled

### ISSUE THREAD

**Issue by IanDominey** [Behat/Symfony2Extension#81]
In behat.yml
```yaml
- FeatureContext:
    queuesToPurge: ['param1', 'param2']
```
Triggers the following warning:
`PHP Warning:  preg_match() expects parameter 2 to be string, array given in /myprojectdir/vendor/behat/symfony2-extension/src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php on line 95`
If I disable the Symfony2 extension, this problem goes away.

Is there a way to pass arrays as parameters without triggering this warning?  I tried wrapping the array inside a string but then the context generates a fatal error because the parameter is type hinted as an array.

**Comment by ciaranmcnulty** [comment]
This looks like a bug, I'll take a look. The only workaround I can think of is to comma-separate in a string then have your context do an `explode`
