### ISSUE TITLE
dead link in the project description

### ISSUE THREAD

**Issue by greg0ire** [Behat/Symfony2Extension#83]
The project description (not under version control, only visible on the github homepage of the project) points to http://extensions.behat.org/symfony2/ `extensions.behat.org` can't event be resolved.

**Comment by stof** [comment]
The behat.org website currently does not list extensions at all anymore, so we don't have an homepage anymore. We are in the process of updating the website, so we will soon have a new link to be displayed. In the meantime, I'm removing the link entirely.
