### ISSUE TITLE
The KernelDictionnary trait is not detected if used embedded in another trait

### ISSUE THREAD

**Issue by julienfastre** [Behat/Symfony2Extension#84]
Consider the following code : 

A trait embedding KernelDictionnary trait
```
trait PersonTrait
{
    use \Behat\Symfony2Extension\Context\KernelDictionary;

    public function doSomethingInPersonTrait() 
    {
        $this->getContainer()->get('service')->doSomething();
        
    }
}
```
And the context class : 
```

class FeatureContext extends MinkContext
{
   use PersonTrait;

   public function doSomethingElse() 
   {
       $this->doSomethingInPersonTrait();
   }
}
```

Will throw this error : `PHP Fatal error:  Call to a member function getContainer() on a non-object`

The Kernel is not set to the Context. The problem reside in `class KernelAwareInitializer` : the function `usesKernelDictionary` does not detects traits recursively.

I am preparing a PR to solve this.

**Comment by stof** [comment]
In the 2.0 version of the extension, we removed the trait detection entirely because it is flawed anyway: a trait does not define a contract at all (you could use a trait but rename the methods when importing it). So the appropriate way to fix it is to implement the interface in your context (the implementation can still be provided by the trait)

**Comment by julienfastre** [comment]
Ok, thanks for your explanations. 

But how to use Kernel in your traits, If you can not ensure that the class which will embed the trait will implements `Behat\Symfony2Extension\Context\KernelAwareContext` ?

I created the PR in the meantime...

**Comment by stof** [comment]
Actually, no. I haven't changed this in Symfony2Extension, but only in MinkExtension. It would make sense to apply it in this extension too

**Comment by sroze** [comment]
Definitely :+1: to remove support of the trait detection.

**Comment by julienfastre** [comment]
I also do agree. I understand now why this is not a good idea :-)
