### ISSUE TITLE
Services as passed as strings if not found

### ISSUE THREAD

**Issue by theofidry** [Behat/Symfony2Extension#89]
When injecting non existent services, they are simply passed as strings instead of raising an error.

**Comment by sroze** [comment]
It is throwing an `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException`.
When we [request the service](https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php#L87), the `ContainerInterface::get` method throws it if the service do not exists.
