### ISSUE TITLE
Error sharing objects between symfony container and behat context

### ISSUE THREAD

**Issue by manelselles** [Behat/Symfony2Extension#90]
I want to use behat to assert that an added entity(highlight) is shown in my homepage.

There is a highlight repository(in memory) service declared in symfony container:

```yaml
highlight_repository:
    class: CustomIntranet\Infraestructure\InMemory\InMemoryHighlightRepository
```
Its simple implementation:
```php
class InMemoryHighlightRepository implements HighlightRepository
{
    private $items = array();

    public function save(Highlight $highlight)
    {
        $this->items[$highlight->id()] = $highlight;
    }

    public function getAll()
    {
        return $this->items;
    }
}
```
And I use it in a controller
```php
    /**
     * @Route("/", name="homepage")
     */
    public function indexAction()
    {
        $highlights = $this->get('highlight_repository')->getAll();
    }
```
Then I inject it into behat context: 
```yaml
default:
    suites:
        web:
            contexts:
                - WebContext:
                    highlightRepository: "@highlight_repository"
```
```php
class WebContext extends RawMinkContext implements Context, SnippetAcceptingContext
{
    private $highlightRepository;

    public function __construct(HighlightRepository $highlightRepository)
    {
        $this->highlightRepository = $highlightRepository;
    }

    /**
     * @Given there is a highlight with title :title and a description :description
     */
    public function thereIsAHighlightWithTitleAndADescription($title, $description)
    {
        $this->highlightRepository->save(
            new Highlight($title, $description)
        );
    }

    /**
     * @When I open the homepage
     */
    public function iOpenTheHomepage()
    {
        $this->visitPath('/');
    }

    /**
     * @Then I should see the highlight title :title
     */
    public function iShouldSeeTheHighlightTitle($title)
    {
        $this->assertSession()->pageTextContains($title);
    }
}
```

The problem is that last assertion throws an exception because the highlight was not really added to the repository because it seems the injected object to Behat context is different from the used in controller.

Any way to have the same object? Any workaround?

**Comment by sroze** [comment]
To be able to inject Symfony services in your Behat context, the extension boots a Symfony kernel and get the services from the container. In the other hand, Mink is kind of browser automation tool, that will uses an URL to access your website, that means that it'll be run in another context: anything you've added in memory in the Behat process won't be accessible.

What you can do is stop using Mink and simply directly use the Symfony kernel (service `@kernel`) to send requests and analyses the responses:
```php
    /**
     * @When I open the homepage
     */
    public function iOpenTheHomepage()
    {
        $this->response = $this->kernel->handle(Request::create('/', 'GET'));
    }

    /**
     * @Then I should see the highlight title :title
     */
    public function iShouldSeeTheHighlightTitle($title)
    {
        $contents = $this->response->getContent();

        // Or any kind of check, either just with strings, Symfony's DomCrawler, or anything...
        if (strpos($contents, $title) === false) {
            throw new \RuntimeException('Not found');
        }
    }
```

**Comment by jon-acker** [comment]
@sroze I found an amazingly simple way to do this, I wonder what you think:
```php
    /**
     * @BeforeScenario
     * @param BeforeScenarioScope $scope
     */
    public function setup(BeforeScenarioScope $scope)
    {
        $this->getMink()->registerSession('test', new Session(new BrowserKitDriver(new Client($this->kernel))));
        $this->getMink()->setDefaultSessionName('test');
    }
```
Effectively this instantiates the HttpKernel\Client with the Symfony kernel provided by Behat - the result is a shared container!! (danger)

It works fine for simple scenarios I've tried.

Of course I would only recommend using this if you're sure you know what you're doing, and what the implications of having direct access to your applications service container for the purpose of testing.
