### ISSUE TITLE
symfony 3 support

### ISSUE THREAD

**Issue by Ma27** [Behat/Symfony2Extension#96]
could you please release in the next time a major release supporting sf3?

**Comment by Ma27** [comment]
ping @stof @everzet

**Comment by thormeier** [comment]
Looks like this going to be fixed with https://github.com/Behat/Symfony2Extension/pull/95, +1, would be cool!

**Comment by Ma27** [comment]
I really hope so ;)

**Comment by sroze** [comment]
Fixed by #95.
